"""Snapshot public GitHub commit activity into commits.js for the site's charts.

All commits on each repo's default branch are counted (not filtered by author),
since some of them were made from an email not linked to the GitHub account.

Usage: GITHUB_TOKEN=... python scripts/update_commits.py
The token is optional (raises the rate limit); only public repos are read either way.
"""
import datetime as dt
import json
import os
import urllib.error
import urllib.request

USER = "Vineel1015"
OUT = os.path.join(os.path.dirname(__file__), "..", "commits.js")
SKIP = {USER}  # profile README repo


def get(url):
    req = urllib.request.Request(url, headers={"Accept": "application/vnd.github+json", "User-Agent": USER})
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(req) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        if e.code == 409:  # empty repository
            return []
        raise


def paged(url):
    page = 1
    while True:
        batch = get(f"{url}{'&' if '?' in url else '?'}per_page=100&page={page}")
        if not batch:
            return
        yield from batch
        page += 1


def monday(d):
    return d - dt.timedelta(days=d.weekday())


repos = [r for r in paged(f"https://api.github.com/users/{USER}/repos?type=owner") if not r["fork"] and r["name"] not in SKIP]
dates = {}
for r in repos:
    commits = paged(f"https://api.github.com/repos/{USER}/{r['name']}/commits")
    dates[r["name"]] = [dt.date.fromisoformat(c["commit"]["author"]["date"][:10]) for c in commits]

all_dates = [d for ds in dates.values() for d in ds]
start = monday(min(all_dates))
end = monday(dt.date.today())
n = (end - start).days // 7 + 1


def weekly(ds):
    w = [0] * n
    for d in ds:
        w[(monday(d) - start).days // 7] += 1
    return w


data = {
    "user": USER,
    "generated": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%MZ"),
    "start": start.isoformat(),
    "total": len(all_dates),
    "weeks": weekly(all_dates),
    "repos": {name: {"total": len(ds), "weeks": weekly(ds)} for name, ds in sorted(dates.items()) if ds},
}
try:
    with open(OUT, encoding="utf-8") as f:
        old = json.loads(f.read().split("= ", 1)[1].rstrip(";\n"))
except (OSError, IndexError, ValueError):
    old = {}
if {**old, "generated": None} == {**data, "generated": None}:
    print("No new commits; commits.js left unchanged")
    raise SystemExit
with open(OUT, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/update_commits.py. Do not edit by hand.\n")
    f.write("window.COMMITS = " + json.dumps(data, separators=(",", ":")) + ";\n")
print(f"{data['total']} commits across {len(data['repos'])} repos, {n} weeks from {start}")
